swagger: '2.0'
info:
  version: '1.0'
  title: edge 07-18-2017
  contact: {}
host: dev-edge-backend.unomiclabs.com:3002
basePath: /
securityDefinitions: {}
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /auth/login:
    post:
      summary: login
      tags:
      - auth
      operationId: login
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/loginrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/controller/Skw5s0wTW/scope:
    put:
      summary: add vnet scope
      tags:
      - controller
      operationId: addvnetscope
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/addvnetscoperequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/controller/:
    post:
      summary: create new Copa Connector
      tags:
      - controller
      operationId: createnewCopaConnector
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createnewCopaConnectorRequest'
      responses:
        200:
          description: ''
          headers: {}
  /device/register/macAddress:
    post:
      summary: preregister by mac
      tags:
      - device
      operationId: preregisterbymac
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/preregisterbymacrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/device/<deviceID>:
    delete:
      summary: delete device
      tags:
      - device
      operationId: deletedevice
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/device/<userID>:
    get:
      summary: get device by id
      tags:
      - device
      operationId: getdevicebyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/device/1:
    put:
      summary: update device by id
      tags:
      - device
      operationId: updatedevicebyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/updatedevicebyidrequest'
      responses:
        200:
          description: ''
          headers: {}
  /group:
    post:
      summary: create new group
      tags:
      - group
      operationId: createnewgroup
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createnewgrouprequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/group:
    delete:
      summary: delete group
      tags:
      - group
      operationId: deletegroup
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: '[future] get groups'
      tags:
      - group
      operationId: '[future]getgroups'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/group/70001:
    get:
      summary: get group by id
      tags:
      - group
      operationId: getgroupbyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/group/70001/team:
    get:
      summary: get team that admins this group
      tags:
      - group
      operationId: getteamthatadminsthisgroup
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/group/70001/devices:
    get:
      summary: get devices in a group
      tags:
      - group
      operationId: getdevicesinagroup
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/group/<groupID>/score:
    get:
      summary: group score
      tags:
      - group
      operationId: groupscore
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/group/150/policy:
    get:
      summary: get group policy
      tags:
      - group
      operationId: getgrouppolicy
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /group/151/inviteMember:
    post:
      summary: invite new member
      tags:
      - group
      operationId: invitenewmember
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/invitenewmemberrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/user/<userID>/registeredDevices:
    get:
      summary: '[archive] get user registered devices'
      tags:
      - group
      operationId: '[archive]getuserregistereddevices'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/organization:
    post:
      summary: create new org
      tags:
      - organization
      operationId: createneworg
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createneworgrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/organization/79:
    get:
      summary: get org by ID
      tags:
      - organization
      operationId: getorgbyID
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
    delete:
      summary: '[future] get org by ID'
      tags:
      - organization
      operationId: '[future]getorgbyID'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/organization/79/teams:
    get:
      summary: get org owned teams
      tags:
      - organization
      operationId: getorgownedteams
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/organization/79/sites:
    get:
      summary: get org owned sites
      tags:
      - organization
      operationId: getorgownedsites
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/organization/<orgID>/orgMembers:
    post:
      summary: invite member to org
      tags:
      - organization
      operationId: invitemembertoorg
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          example: >-
            {

            "userID"<invitee user id>

            }
          type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/site:
    post:
      summary: create new site
      tags:
      - site
      operationId: createnewsite
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createnewsiterequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/site/<siteID>:
    get:
      summary: get site by id
      tags:
      - site
      operationId: getsitebyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/site/<siteID>/switches:
    get:
      summary: get site switches
      tags:
      - site
      operationId: getsiteswitches
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
    post:
      summary: add site switch
      tags:
      - site
      operationId: addsiteswitch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/addsiteswitchrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/site/105/controller:
    put:
      summary: Change Controller
      tags:
      - site
      operationId: ChangeController
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ChangeControllerRequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/site/31/switches:
    put:
      summary: update site switch
      tags:
      - site
      operationId: updatesiteswitch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/updatesiteswitchrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/site/52:
    delete:
      summary: '[future] delete site by id'
      tags:
      - site
      operationId: '[future]deletesitebyid'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/site/:
    get:
      summary: '[future] get sites'
      tags:
      - site
      operationId: '[future]getsites'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/:
    post:
      summary: create a team
      tags:
      - teams
      operationId: createateam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createateamrequest'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: '[future] get all teams'
      tags:
      - teams
      operationId: '[future]getallteams'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/42:
    get:
      summary: get team by Id
      tags:
      - teams
      operationId: getteambyId
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/42/devices:
    get:
      summary: get devices admined by a team
      tags:
      - teams
      operationId: getdevicesadminedbyateam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/42/groups:
    get:
      summary: get groups/zones admined by a team
      tags:
      - teams
      operationId: getgroups/zonesadminedbyateam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/42/sites:
    get:
      summary: get sites admined by team
      tags:
      - teams
      operationId: getsitesadminedbyteam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/search:
    post:
      summary: team search
      tags:
      - teams
      operationId: teamsearch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/teamsearchrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/team/<teamID>/teamMembers:
    post:
      summary: invite member to team
      tags:
      - teams
      operationId: invitemembertoteam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          example: >-
            {
            	"userID": <userID>,
            	"role": <teamAdmin or member>
            }
          type: string
      responses:
        200:
          description: ''
          headers: {}
    put:
      summary: update user role for team
      tags:
      - teams
      operationId: updateuserroleforteam
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          example: >-
            {
            	"userID": <userID>,
            	"role": <teamAdmin or member>
            }
          type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/team/48:
    delete:
      summary: '[future] delete a team'
      tags:
      - teams
      operationId: '[future]deleteateam'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /api/user:
    post:
      summary: create new user
      tags:
      - user
      operationId: createnewuser
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/createnewuserrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/user/584a1485cb3015983d4f0b16:
    delete:
      summary: delete user by id
      tags:
      - user
      operationId: deleteuserbyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001:
    get:
      summary: get user by id
      tags:
      - user
      operationId: getuserbyid
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001/groups:
    get:
      summary: get user groups
      tags:
      - user
      operationId: getusergroups
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001/teams:
    get:
      summary: get user teams
      tags:
      - user
      operationId: getuserteams
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001/sites:
    get:
      summary: get user's site
      tags:
      - user
      operationId: getuser'ssite
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001/organizations:
    get:
      summary: get user's org
      tags:
      - user
      operationId: getuser'sorg
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/10001/devices:
    get:
      summary: get user devices
      tags:
      - user
      operationId: getuserdevices
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/<userID>/updatePassword:
    put:
      summary: update user password
      tags:
      - user
      operationId: updateuserpassword
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          example: >-
            {
            	"password":<new_password>
            }
          type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/<userID>:
    put:
      summary: update user
      tags:
      - user
      operationId: updateuser
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/user/search:
    post:
      summary: user search
      tags:
      - user
      operationId: usersearch
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/usersearchrequest'
      responses:
        200:
          description: ''
          headers: {}
  /api/user/:
    get:
      summary: '[archive] get users'
      tags:
      - user
      operationId: '[archive]getusers'
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /api/ruleTemplate/class/types:
    get:
      summary: get rule template classes
      tags:
      - policy
      operationId: getruletemplateclasses
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /version:
    get:
      summary: version
      tags:
      - Misc
      operationId: version
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
definitions:
  loginrequest:
    title: loginrequest
    example:
      username: jeb@unomicedge.com
      password: unomicIs#1
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
    - username
    - password
  addvnetscoperequest:
    title: addvnetscoperequest
    example:
      vnet:
      - VmwareOvsOnTeamViewer
      - VmwareOvsS2OnTeamViewer
    type: object
    properties:
      vnet:
        type: array
        items:
          type: string
    required:
    - vnet
  createnewCopaConnectorRequest:
    title: createnewCopaConnectorRequest
    example:
      controllerInfo:
        CONTROLLER_IP: 172.20.0.5
        CONTROLLER_PASSWORD: admin
        CONTROLLER_USERNAME: Administrator
        CONTROLLER_PORT: 8080
        _id: local_computer
    type: object
    properties:
      controllerInfo:
        $ref: '#/definitions/ControllerInfo'
    required:
    - controllerInfo
  ControllerInfo:
    title: ControllerInfo
    example:
      CONTROLLER_IP: 172.20.0.5
      CONTROLLER_PASSWORD: admin
      CONTROLLER_USERNAME: Administrator
      CONTROLLER_PORT: 8080
      _id: local_computer
    type: object
    properties:
      CONTROLLER_IP:
        type: string
      CONTROLLER_PASSWORD:
        type: string
      CONTROLLER_USERNAME:
        type: string
      CONTROLLER_PORT:
        type: string
      _id:
        type: string
    required:
    - CONTROLLER_IP
    - CONTROLLER_PASSWORD
    - CONTROLLER_USERNAME
    - CONTROLLER_PORT
    - _id
  preregisterbymacrequest:
    title: preregisterbymacrequest
    example:
      macAddress: 00:0C:29:18:3F:3F
      name: switch1Devices
      deviceType: VMWare_VM
    type: object
    properties:
      macAddress:
        type: string
      name:
        type: string
      deviceType:
        type: string
    required:
    - macAddress
    - name
    - deviceType
  updatedevicebyidrequest:
    title: updatedevicebyidrequest
    example:
      id: 1
      name: raspberry pi
      deviceType: laptop
      activeGroupID: 1
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      deviceType:
        type: string
      activeGroupID:
        type: integer
        format: int32
    required:
    - id
    - name
    - deviceType
    - activeGroupID
  createnewgrouprequest:
    title: createnewgrouprequest
    example:
      name: test zone for team 42
      teamID: 42
    type: object
    properties:
      name:
        type: string
      teamID:
        type: string
    required:
    - name
    - teamID
  invitenewmemberrequest:
    title: invitenewmemberrequest
    example:
      userID: michael@unomicedge.com
    type: object
    properties:
      userID:
        type: string
    required:
    - userID
  DeleteamemberfromthegroupRequest:
    title: DeleteamemberfromthegroupRequest
    example:
      userID: michael@unomicedge.com
    type: object
    properties:
      userID:
        type: string
    required:
    - userID
  createneworgrequest:
    title: createneworgrequest
    example:
      name: test Org
      orgAdminID: 10001
      email: emailme@me.com
      phone: 1234567890
      location:
        city: my city
        zip: 12345
        state: CA
        country: US
    type: object
    properties:
      name:
        type: string
      orgAdminID:
        type: integer
        format: int32
      email:
        type: string
      phone:
        type: string
      location:
        $ref: '#/definitions/Location'
    required:
    - name
    - orgAdminID
    - email
    - phone
    - location
  Location:
    title: Location
    example:
      city: my city
      zip: 12345
      state: CA
      country: US
    type: object
    properties:
      city:
        type: string
      zip:
        type: string
      state:
        type: string
      country:
        type: string
    required:
    - city
    - zip
    - state
    - country
  createnewsiterequest:
    title: createnewsiterequest
    example:
      siteName: the test1 -delme
      teamID: 42
      orgID: 75
      createController: false
      location:
        addressLine1: 1230 alive drive
        addressLine2: 
        city: my city
        zip: 12345
        state: CA
        country: US
    type: object
    properties:
      siteName:
        type: string
      teamID:
        type: integer
        format: int32
      orgID:
        type: integer
        format: int32
      createController:
        type: boolean
      location:
        $ref: '#/definitions/Location1'
    required:
    - siteName
    - teamID
    - orgID
    - createController
    - location
  Location1:
    title: Location1
    example:
      addressLine1: 1230 alive drive
      addressLine2: 
      city: my city
      zip: 12345
      state: CA
      country: US
    type: object
    properties:
      addressLine1:
        type: string
      addressLine2:
        type: string
      city:
        type: string
      zip:
        type: string
      state:
        type: string
      country:
        type: string
    required:
    - addressLine1
    - addressLine2
    - city
    - zip
    - state
    - country
  ChangeControllerRequest:
    title: ChangeControllerRequest
    example:
      controllerID: Skw5s0wTW
    type: object
    properties:
      controllerID:
        type: string
    required:
    - controllerID
  addsiteswitchrequest:
    title: addsiteswitchrequest
    example:
      switchConfig:
        name: test switch
        dpid: test dpid
        macAddress: 11:22:33:44:55:66
        ipAddress: 1.2.3.4
        gatewayIp: 11.12.13.14
        gatewayMac: 01.02.03.04.05.06
        unmanagedPorts: []
        managedPorts: []
    type: object
    properties:
      switchConfig:
        $ref: '#/definitions/SwitchConfig'
    required:
    - switchConfig
  SwitchConfig:
    title: SwitchConfig
    example:
      name: test switch
      dpid: test dpid
      macAddress: 11:22:33:44:55:66
      ipAddress: 1.2.3.4
      gatewayIp: 11.12.13.14
      gatewayMac: 01.02.03.04.05.06
      unmanagedPorts: []
      managedPorts: []
    type: object
    properties:
      name:
        type: string
      dpid:
        type: string
      macAddress:
        type: string
      ipAddress:
        type: string
      gatewayIp:
        type: string
      gatewayMac:
        type: string
      unmanagedPorts:
        type: array
        items:
          type: string
      managedPorts:
        type: array
        items:
          type: string
    required:
    - name
    - dpid
    - macAddress
    - ipAddress
    - gatewayIp
    - gatewayMac
    - unmanagedPorts
    - managedPorts
  updatesiteswitchrequest:
    title: updatesiteswitchrequest
    example:
      switchConfig:
        name: test switch
        dpid: test dpid
        macAddress: 11:22:33:44:55:66
        ipAddress: 1.2.3.4
        gatewayIp: 11.12.13.14
        gatewayMac: 01.02.03.04.05.06
        unmanagedPorts: []
        managedPorts: []
    type: object
    properties:
      switchConfig:
        $ref: '#/definitions/SwitchConfig'
    required:
    - switchConfig
  createateamrequest:
    title: createateamrequest
    example:
      userID: 10001
      name: testTeamToBeDeleted
      description: A team that will be used to see if delete REST endpoint works.
      personal: false
      orgID: 75
    type: object
    properties:
      userID:
        type: integer
        format: int32
      name:
        type: string
      description:
        type: string
      personal:
        type: boolean
      orgID:
        type: integer
        format: int32
    required:
    - userID
    - name
    - description
    - personal
    - orgID
  teamsearchrequest:
    title: teamsearchrequest
    example:
      search:
        personal: true
    type: object
    properties:
      search:
        $ref: '#/definitions/Search'
    required:
    - search
  Search:
    title: Search
    example:
      personal: true
    type: object
    properties:
      personal:
        type: boolean
    required:
    - personal
  createnewuserrequest:
    title: createnewuserrequest
    example:
      username: chris@home.com
      password: password
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
    - username
    - password
  usersearchrequest:
    title: usersearchrequest
    example:
      search:
        firstName: chris
    type: object
    properties:
      search:
        $ref: '#/definitions/Search1'
    required:
    - search
  Search1:
    title: Search1
    example:
      firstName: chris
    type: object
    properties:
      firstName:
        type: string
    required:
    - firstName
tags:
- name: auth
- name: controller
- name: device
- name: group
- name: organization
- name: site
- name: teams
  description: team api calls
- name: user
- name: policy
- name: Misc
  description: ''
